<table border=0 cellpadding=0 cellspacing=0 width=810 class="m-auto" style='border-collapse:
 collapse;width:606pt'>
    <tr height=24 style='mso-height-source:userset;height:18.0pt'>
        <td colspan=4 height=24 width=257 style='height:18.0pt;width:192pt' align=left valign=top>
            <span
                style='mso-ignore:vglayout; position:absolute;z-index:1;margin-left:4px;margin-top:15px;width:285px;height:72px'>
                <img width=285 height=72 src="{{ asset('logo.png') }}"></span>
            <span style='mso-ignore:vglayout2'>
                <table cellpadding=0 cellspacing=0>
                    <tr>
                        <td colspan=4 height=24 class=xl179 width=257 style='height:18.0pt; width:192pt'>&nbsp;</td>
                    </tr>
                </table>
            </span>
        </td>
        <td class=xl68 style='border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl94 style='border-top:none;border-left:none'>Date:</td>
        <td class=xl95 style='border-left:none'>&nbsp;</td>
        <td colspan=2 class="xl163 pl-1" style='border-right:.5pt solid #B2B2B2'>{{ $date }}</td>
    </tr>
    <tr height=24 style='mso-height-source:userset;height:18.0pt'>
        <td colspan=4 height=24 class=xl180 style='height:18.0pt'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl94 style='border-top:none;border-left:none'>Society ID<span style='display:none'>e #:</span>
        </td>
        <td class=xl95 style='border-top:none;border-left:none'>&nbsp;</td>
        <td colspan=2 class="xl163 pl-1" style='border-right:.5pt solid #B2B2B2'>{{ $society->society_id }}
        </td>
    </tr>
    <tr height=24 style='mso-height-source:userset;height:18.0pt'>
        <td height=24 class=xl69 style='height:18.0pt;border-top:none'>&nbsp;</td>
        <td class=xl69 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl69 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl69 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl94 style='border-top:none;border-left:none'>Society Starting Date:</span>
        </td>
        <td class=xl95 style='border-top:none;border-left:none'>&nbsp;</td>
        <td colspan=2 class="xl163 pl-1" style='border-right:.5pt solid #B2B2B2'>
            {{ date('jS M Y', strtotime($society->society_start)) }}</td>
    </tr>
    <tr height=24 style='mso-height-source:userset;height:18.0pt'>
        <td height=24 class=xl69 style='height:18.0pt;border-top:none'>&nbsp;</td>
        <td class=xl69 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl69 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl69 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl94 style='border-top:none;border-left:none'>Society Ending Date</span>
        </td>
        <td class=xl95 style='border-top:none;border-left:none'>&nbsp;</td>
        <td colspan=2 class="xl163 pl-1" style='border-right:.5pt solid #B2B2B2'>
            {{ date('jS M Y', strtotime($society->society_end)) }}</td>
    </tr>
    <tr height=24 style='mso-height-source:userset;height:18.0pt'>
        <td height=24 class=xl69 style='height:18.0pt;border-top:none'>&nbsp;</td>
        <td class=xl69 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl69 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl69 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl94 style='border-top:none;border-left:none'>Report Generated By:</span>
        </td>
        <td class=xl95 style='border-top:none;border-left:none'>&nbsp;</td>
        <td colspan=2 class="xl163 pl-1" style='border-right:.5pt solid #B2B2B2'>{{  auth()->user()->name }}
        </td>
    </tr>
    <tr height=9 style='mso-height-source:userset;height:7.5pt'>
        <td height=9 class=xl69 style='height:7.5pt;border-top:none'>&nbsp;</td>
        <td class=xl69 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl69 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl69 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl70 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl76 style='border-left:none'>&nbsp;</td>
        <td class=xl76 style='border-left:none'>&nbsp;</td>
        <td class=xl76 style='border-left:none'>&nbsp;</td>
    </tr>

    <tr height=24 style='mso-height-source:userset;height:18.0pt'>
        <td colspan=4 height=24 class=xl165 style='height:18.0pt'>Member Details</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td colspan=4 class=xl165 style='border-left:none'>Society Summary</td>
    </tr>
    <tr height=24 style='mso-height-source:userset;height:18.0pt; width:10px'>
        <td colspan=4 height=24 class=xl153 style='height:18.0pt'>Total No of Members :
            {{ $members->count(); }}</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td colspan=4 class="xl153" style='border-left:none;'>Society Name : {{ $society->name }}
        </td>
    </tr>
    <tr height=24 style='mso-height-source:userset;height:18.0pt'>
        <td colspan=4 height=24 class=xl153 style='height:18.0pt'>Total Number of Shares :
            {{ $members->sum('share_no') }}</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td colspan=4 class=xl153 style='border-left:none'>One Share Value : ₹ {{ $society->share_value }}/-
        </td>
    </tr>
    <tr height=24 style='mso-height-source:userset;height:18.0pt'>
        <td colspan=4 height=24 class=xl153 style='height:18.0pt'>Society Admin : @foreach ($admins as $admin)
            {{ $admin->name }}. @endforeach</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td colspan=4 class=xl153 style='border-left:none'>Lending Interest rate (%)
            : {{ $society->lending_interest_rate }}</td>
    </tr>
    <tr height=24 style='mso-height-source:userset;height:18.0pt'>
        <td colspan=4 height=24 class=xl153 style='height:18.0pt'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td colspan=4 class=xl153 style='border-left:none'>Address : {{ $society->address }}</td>
    </tr>
    <tr height=24 style='mso-height-source:userset;height:18.0pt'>
        <td colspan=4 height=24 class=xl153 style='height:18.0pt'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl65 style='border-top:none;border-left:none'>&nbsp;</td>
        <td colspan=4 class=xl153 style='border-left:none'>Phone : {{ $society->phone_no }}<span
                style='mso-spacerun:yes'> </span></td>
    </tr>
    <tr height=9 style='mso-height-source:userset;height:7.5pt'>
        <td height=9 class=xl72 style='height:7.5pt;border-top:none'>&nbsp;</td>
        <td class=xl72 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl72 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl72 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl73 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl73 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl73 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl73 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl73 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl73 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl73 style='border-top:none;border-left:none'>&nbsp;</td>
        <td class=xl73 style='border-top:none;border-left:none'>&nbsp;</td>
    </tr>
</table>